// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuanCaPhe.Data;

#nullable disable

namespace QuanLyQuanCaPhe.Migrations
{
    [DbContext(typeof(QLCPDbContext))]
    [Migration("20260129035327_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Ban", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("Bàn mới");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Trống");

                    b.HasKey("ID");

                    b.ToTable("Ban", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("LuongThucTe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Chưa trả");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV");

                    b.ToTable("BangLuong", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.CaLam", b =>
                {
                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenCa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCa");

                    b.ToTable("CaLam", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ChamCong", b =>
                {
                    b.Property<int>("MaCham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(510)
                        .HasColumnType("nvarchar(510)");

                    b.Property<int?>("MaCa")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("date");

                    b.HasKey("MaCham");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(23,2)");

                    b.HasKey("ChiTietID");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.CongThuc", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<string>("MaNL")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("MaCT");

                    b.HasIndex("MaNL");

                    b.HasIndex("MaSP");

                    b.ToTable("CongThuc", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("char(8)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(510)
                        .HasColumnType("nvarchar(510)");

                    b.Property<decimal?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("MaKH")
                        .HasColumnType("char(6)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.Property<int>("idBan")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.HasIndex("idBan");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.InventoryMovements", b =>
                {
                    b.Property<int>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementID"));

                    b.Property<decimal>("ChangeQty")
                        .HasColumnType("decimal(12,3)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MaNL")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("MovementType")
                        .HasMaxLength(510)
                        .HasColumnType("nvarchar(510)");

                    b.Property<string>("RefMaHD")
                        .HasColumnType("char(8)");

                    b.HasKey("MovementID");

                    b.HasIndex("MaNL");

                    b.HasIndex("RefMaHD");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("char(6)");

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SDT")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NguyenLieu", b =>
                {
                    b.Property<string>("MaNL")
                        .HasColumnType("char(6)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenNL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MaNL");

                    b.ToTable("NguyenLieu", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("char(6)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Đang làm");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ImagePath")
                        .HasMaxLength(510)
                        .HasColumnType("nvarchar(510)");

                    b.Property<string>("LoaiSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Còn bán");

                    b.HasKey("MaSP");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MaNV")
                        .HasColumnType("char(6)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Nhân viên");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.BangLuong", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.NhanVien", "NhanVien")
                        .WithMany("BangLuong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ChamCong", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.CaLam", "CaLam")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyQuanCaPhe.Data.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CaLam");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.SanPham", "SanPham")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.CongThuc", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.NguyenLieu", "NguyenLieu")
                        .WithMany("CongThuc")
                        .HasForeignKey("MaNL")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.SanPham", "SanPham")
                        .WithMany("CongThuc")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyQuanCaPhe.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.Ban", "Ban")
                        .WithMany("HoaDon")
                        .HasForeignKey("idBan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.InventoryMovements", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.NguyenLieu", "NguyenLieu")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("MaNL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.HoaDon", "HoaDon")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("RefMaHD")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HoaDon");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyQuanCaPhe.Data.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.Ban", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.CaLam", b =>
                {
                    b.Navigation("ChamCong");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NguyenLieu", b =>
                {
                    b.Navigation("CongThuc");

                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.NhanVien", b =>
                {
                    b.Navigation("BangLuong");

                    b.Navigation("ChamCong");

                    b.Navigation("HoaDon");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("CongThuc");
                });
#pragma warning restore 612, 618
        }
    }
}
